#ifndef QTREADABILITY_GLOBAL_H
#define QTREADABILITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTREADABILITY_LIBRARY)
#  define QTREADABILITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTREADABILITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTREADABILITY_GLOBAL_H
